variables:
  CONAN_REFERENCE: "jom/1.1.2"
  CONAN_USERNAME: "sight"
  CONAN_CHANNEL: "stable"
  CONAN_ARCHS: x86_64

stages:
  - build

msvc2017:
  stage: build
  variables:
    CONAN_VISUAL_VERSIONS: "15"
    CONAN_USER_HOME: $CI_PROJECT_DIR
  script:
    - git -c http.sslVerify=false clone --depth 1 https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lan.local/conan/conan.git
    - python conan/gitlab-ci/build.py
  tags:
    - shell
    - windows